const WA='21644379166';
const products=[
{id:1,name:'Ruban LED RGB 5050',price:25,cat:'Rubans LED',img:'images/ruban-rgb-5050.jpg',badge:'Best Seller',desc:'Ruban RGB 5050 avec télécommande pour créer une ambiance colorée.'},
{id:2,name:'Ampoule LED RGB E27',price:15,cat:'Ampoules',img:'images/ampoule-rgb-e27.jpg',badge:'Populaire',desc:'Ampoule E27 RGB avec télécommande, idéale pour chambres et décoration.'},
{id:3,name:'Panneaux LED hexagonaux',price:45,cat:'Décoration',img:'images/panneaux-hexagonaux.webp',badge:'Nouveau',desc:'Panneaux hexagonaux lumineux pour mur gaming, bureau ou salon.'},
{id:4,name:'Spot LED encastrable',price:8,cat:'Spots LED',img:'images/spot-led.jpg',badge:'Essentiel',desc:'Spot LED rond encastrable pour un éclairage propre et moderne.'}
];
let cart=JSON.parse(localStorage.getItem('luxora_cart')||'[]');let fav=JSON.parse(localStorage.getItem('luxora_fav')||'[]');let activeCat='Tous';let modalProduct=null;let modalQty=1;
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem('luxora_cart',JSON.stringify(cart));localStorage.setItem('luxora_fav',JSON.stringify(fav))}
function money(n){return `${n.toFixed(0)} TND`}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function renderChips(){const cats=['Tous',...new Set(products.map(p=>p.cat))];$('#chips').innerHTML=cats.map(c=>`<button class="chip ${c===activeCat?'active':''}" data-cat="${c}">${c}</button>`).join('');$$('.chip').forEach(b=>b.onclick=()=>{activeCat=b.dataset.cat;renderChips();renderProducts()})}
function renderProducts(){const q=$('#search').value.trim().toLowerCase();let arr=products.filter(p=>(activeCat==='Tous'||p.cat===activeCat)&&(!q||(p.name+' '+p.cat+' '+p.desc).toLowerCase().includes(q)));const sort=$('#sort').value;if(sort==='low')arr.sort((a,b)=>a.price-b.price);if(sort==='high')arr.sort((a,b)=>b.price-a.price);if(sort==='az')arr.sort((a,b)=>a.name.localeCompare(b.name));$('#empty').hidden=arr.length>0;$('#products').innerHTML=arr.map(p=>`<article class="card"><span class="badge">${p.badge}</span><img class="product-img" src="${p.img}" alt="${p.name}" loading="lazy"><div class="card-body"><div class="card-cat">${p.cat}</div><h3>${p.name}</h3><p class="card-desc">${p.desc}</p><div class="price-row"><strong class="price">${money(p.price)}</strong><div class="card-actions"><button class="round heart ${fav.includes(p.id)?'active':''}" data-fav="${p.id}">♡</button><button class="round" data-view="${p.id}">⌕</button><button class="add" data-add="${p.id}">Ajouter</button></div></div></div></article>`).join('');$$('[data-add]').forEach(b=>b.onclick=()=>addCart(+b.dataset.add,1));$$('[data-view]').forEach(b=>b.onclick=()=>openProduct(+b.dataset.view));$$('[data-fav]').forEach(b=>b.onclick=()=>toggleFav(+b.dataset.fav))}
function toggleFav(id){fav.includes(id)?fav=fav.filter(x=>x!==id):fav.push(id);save();renderProducts();toast(fav.includes(id)?'Ajouté aux favoris ♥':'Retiré des favoris')}
function addCart(id,qty=1){const p=products.find(x=>x.id===id);const item=cart.find(x=>x.id===id);if(item)item.qty+=qty;else cart.push({id,qty});save();renderCart();openCart();toast(`${p.name} ajouté au panier`)}
function setQty(id,qty){const x=cart.find(i=>i.id===id);if(!x)return;if(qty<=0)cart=cart.filter(i=>i.id!==id);else x.qty=qty;save();renderCart()}
function renderCart(){let count=cart.reduce((s,x)=>s+x.qty,0),sub=cart.reduce((s,x)=>{const p=products.find(p=>p.id===x.id);return s+p.price*x.qty},0);$('#cartCount').textContent=count;$('#subtotal').textContent=money(sub);$('#total').textContent=money(sub);$('#cartItems').innerHTML=cart.length?cart.map(x=>{const p=products.find(p=>p.id===x.id);return `<div class="cart-item"><img src="${p.img}" alt=""><div><h4>${p.name}</h4><small>${money(p.price)} × ${x.qty}</small><div class="cart-qty"><button data-dec="${p.id}">−</button><b>${x.qty}</b><button data-inc="${p.id}">+</button></div></div><button class="cart-remove" data-rem="${p.id}">×</button></div>`}).join(''):`<div class="empty">Votre panier est vide.<br><a href="#shop" class="btn gold" style="margin-top:15px">Voir les produits</a></div>`;$$('[data-dec]').forEach(b=>b.onclick=()=>setQty(+b.dataset.dec,(cart.find(x=>x.id==b.dataset.dec)?.qty||1)-1));$$('[data-inc]').forEach(b=>b.onclick=()=>setQty(+b.dataset.inc,(cart.find(x=>x.id==b.dataset.inc)?.qty||0)+1));$$('[data-rem]').forEach(b=>b.onclick=()=>setQty(+b.dataset.rem,0))}
function openCart(){$('#cartDrawer').classList.add('open');$('#overlay').classList.add('show')}function closeCart(){$('#cartDrawer').classList.remove('open');$('#overlay').classList.remove('show')}
function openProduct(id){const p=products.find(x=>x.id===id);modalProduct=p;modalQty=1;$('#modalImg').src=p.img;$('#modalImg').alt=p.name;$('#modalCat').textContent=p.cat;$('#modalTitle').textContent=p.name;$('#modalDesc').textContent=p.desc;$('#modalPrice').textContent=money(p.price);$('#modalQty').textContent=1;$('#productModal').classList.add('open')}
function closeModal(id){$('#'+id).classList.remove('open')}
function checkout(){if(!cart.length){toast('Ajoutez au moins un produit au panier');return}closeCart();$('#checkoutModal').classList.add('open')}
function buildWhatsApp(e){e.preventDefault();if(!cart.length){toast('Votre panier est vide');return}const name=$('#customerName').value.trim(),phone=$('#customerPhone').value.trim(),gov=$('#governorate').value,address=$('#address').value.trim();let sub=0;let lines=cart.map(x=>{const p=products.find(p=>p.id===x.id);sub+=p.price*x.qty;return `• ${p.name} × ${x.qty} = ${p.price*x.qty} TND`}).join('\n');const msg=`Bonjour LUXORA 👋\n\nJe souhaite passer une commande.\n\n${lines}\n\nSous-total : ${sub} TND\n\nNom : ${name}\nTéléphone : ${phone}\nGouvernorat : ${gov}\nAdresse / remarque : ${address||'—'}\n\nMerci de confirmer la disponibilité, les frais de livraison et le total.`;window.open(`https://wa.me/${WA}?text=${encodeURIComponent(msg)}`,'_blank');}
$('#search').addEventListener('input',renderProducts);$('#sort').addEventListener('change',renderProducts);$('#cartOpen').onclick=openCart;$('#cartClose').onclick=closeCart;$('#overlay').onclick=closeCart;$('#checkoutOpen').onclick=checkout;$('#clearCart').onclick=()=>{cart=[];save();renderCart();toast('Panier vidé')};$('#modalAdd').onclick=()=>{addCart(modalProduct.id,modalQty);closeModal('productModal')};$('#modalMinus').onclick=()=>{modalQty=Math.max(1,modalQty-1);$('#modalQty').textContent=modalQty};$('#modalPlus').onclick=()=>{modalQty++;$('#modalQty').textContent=modalQty};$$('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));$('#checkoutForm').addEventListener('submit',buildWhatsApp);$('#hamb').onclick=()=>$('#nav').classList.toggle('open');$('#themeBtn').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('luxora_theme',document.body.classList.contains('light')?'light':'dark')};$('#langBtn').onclick=()=>toast('Version arabe : structure prête — contenu principal disponible en français');
if(localStorage.getItem('luxora_theme')==='light')document.body.classList.add('light');renderChips();renderProducts();renderCart();
