const products=[
{id:1,name:'Ruban LED RGB 5050 — 5m',price:25,cat:'rgb',tag:'RGB',img:'images/ruban-rgb.jpg',desc:'Ruban LED RGB 5050 avec télécommande et alimentation. Idéal pour TV, chambre, salon, bureau et décoration.'},
{id:2,name:'Ampoule LED RGB E27',price:15,cat:'rgb',tag:'SMART LIGHT',img:'images/ampoule-rgb.jpg',desc:'Ampoule E27 RGB avec télécommande, idéale pour créer différentes ambiances lumineuses.'},
{id:3,name:'Panneaux LED hexagonaux',price:45,cat:'decor',tag:'DÉCORATION',img:'images/panneaux-hex.jpg',desc:'Panneaux lumineux hexagonaux pour décoration murale, gaming, chambre et espace de travail.'},
{id:4,name:'Spot LED encastrable',price:8,cat:'spot',tag:'ÉCLAIRAGE',img:'images/spot-led.jpg',desc:'Spot LED rond encastrable avec driver, adapté à l’éclairage intérieur.'}
];
let cart=JSON.parse(localStorage.getItem('luxoraCart')||'[]');
let lang=localStorage.getItem('luxoraLang')||'fr';
const wa='21644379166';
const $=s=>document.querySelector(s);
function save(){localStorage.setItem('luxoraCart',JSON.stringify(cart));renderCart();}
function renderProducts(){const grid=$('#productGrid'),q=$('#search').value.trim().toLowerCase(),cat=document.querySelector('.filter.active').dataset.cat;const list=products.filter(p=>(cat==='all'||p.cat===cat)&&(!q||p.name.toLowerCase().includes(q)||p.tag.toLowerCase().includes(q)));grid.innerHTML=list.map(p=>`<article class="card"><img class="product-img" src="${p.img}" alt="${p.name}" data-id="${p.id}"><p class="tag">${p.tag}</p><h3>${p.name}</h3><div class="price">${p.price} TND</div><div class="card-actions"><button class="add" data-add="${p.id}">${lang==='ar'?'أضف للسلة':'Ajouter'}</button><button class="details" data-details="${p.id}">${lang==='ar'?'التفاصيل':'Détails'}</button></div></article>`).join('');$('#empty').style.display=list.length?'none':'block';grid.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>add(+b.dataset.add));grid.querySelectorAll('[data-details],.product-img').forEach(b=>b.onclick=()=>openModal(+b.dataset.details||+b.dataset.id));}
function add(id){const item=cart.find(x=>x.id===id);item?item.qty++:cart.push({id,qty:1});save();openCart();}
function change(id,d){const item=cart.find(x=>x.id===id);if(!item)return;item.qty+=d;if(item.qty<=0)cart=cart.filter(x=>x.id!==id);save();}
function renderCart(){const box=$('#cartItems');$('#cartCount').textContent=cart.reduce((s,x)=>s+x.qty,0);let total=0;box.innerHTML=cart.length?cart.map(x=>{const p=products.find(y=>y.id===x.id);total+=p.price*x.qty;return `<div class="cart-row"><img src="${p.img}" alt=""><div><b>${p.name}</b><small>${p.price} TND × ${x.qty}</small><div class="qty"><button data-minus="${p.id}">−</button><span>${x.qty}</span><button data-plus="${p.id}">+</button></div></div><button class="remove" data-remove="${p.id}">Supprimer</button></div>`}).join(''):`<p class="muted">${lang==='ar'?'السلة فارغة.':'Votre panier est vide.'}</p>`;$('#cartTotal').textContent=total+' TND';box.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>change(+b.dataset.minus,-1));box.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>change(+b.dataset.plus,1));box.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{cart=cart.filter(x=>x.id!==+b.dataset.remove);save()});}
function openCart(){$('#cartPanel').classList.add('open');$('#overlay').classList.add('show')}
function closeCart(){$('#cartPanel').classList.remove('open');$('#overlay').classList.remove('show')}
function openModal(id){const p=products.find(x=>x.id===id);$('#modalContent').innerHTML=`<div class="modal-product"><img src="${p.img}" alt="${p.name}"><div><p class="eyebrow">${p.tag}</p><h2>${p.name}</h2><div class="price">${p.price} TND</div><p>${p.desc}</p><button class="btn gold" onclick="add(${p.id});closeModal()">${lang==='ar'?'أضف للسلة':'Ajouter au panier'}</button></div></div>`;$('#productModal').classList.add('show');$('#overlay').classList.add('show')}
function closeModal(){$('#productModal').classList.remove('show');if(!$('#cartPanel').classList.contains('open'))$('#overlay').classList.remove('show')}
function order(){if(!cart.length){alert(lang==='ar'?'السلة فارغة.':'Votre panier est vide.');return}let total=0;let msg=lang==='ar'?'مرحباً LUXORA، أريد طلب:%0A':'Bonjour LUXORA, je souhaite commander :%0A';cart.forEach(x=>{const p=products.find(y=>y.id===x.id);total+=p.price*x.qty;msg+=`• ${encodeURIComponent(p.name)} × ${x.qty}%0A`});msg+=`%0A${lang==='ar'?'المجموع':'Total'} : ${total} TND`;window.open(`https://wa.me/${wa}?text=${msg}`,'_blank')}
function applyLang(){document.documentElement.lang=lang;document.body.classList.toggle('ar',lang==='ar');document.querySelectorAll('[data-fr]').forEach(el=>{el.textContent=el.dataset[lang]});$('#langBtn').textContent=lang==='fr'?'AR':'FR';renderProducts();renderCart()}
$('#search').addEventListener('input',renderProducts);document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderProducts()});$('#cartBtn').onclick=openCart;$('#closeCart').onclick=closeCart;$('#overlay').onclick=()=>{closeCart();closeModal()};$('#closeModal').onclick=closeModal;$('#orderBtn').onclick=order;$('#langBtn').onclick=()=>{lang=lang==='fr'?'ar':'fr';localStorage.setItem('luxoraLang',lang);applyLang()};renderProducts();renderCart();applyLang();
